import type { MenuItem, Offer, Category, SubCategory } from './types';
import { Dietary } from './types';

export const CATEGORIES: (Category | 'All')[] = ['All', 'Starters', 'Main Course', 'Desserts', 'Drinks'];

export const SUB_CATEGORIES_MAP: Record<Category, (SubCategory | 'All')[]> = {
    'Starters': ['All', 'Tandoori', 'Soups'],
    'Main Course': ['All', 'Biryani', 'Curries', 'Chinese', 'Breads'],
    'Desserts': ['All', 'Cakes', 'Traditional'],
    'Drinks': ['All', 'Hot', 'Cold'],
};


export const OFFERS: Offer[] = [
    { 
        id: 1, 
        title: "Biryani Feast", 
        description: "An unbeatable combo for the discerning palate. Perfect for sharing.", 
        imageUrl: 'https://i.ibb.co/Tx7VX5pD/Gemini-Generated-Image-5wen95wen95wen95.png',
        items: ['Chicken Biryani', 'Mandi', 'Soft Drinks'],
        originalPrice: 750,
        discountedPrice: 599
    },
    { 
        id: 2, 
        title: "Tandoori Platter", 
        description: "A sizzling selection of our best tandoori starters.", 
        imageUrl: 'https://i.ibb.co/tRQDLdW/Gemini-Generated-Image-a491rra491rra491.png',
        items: ['Paneer Tikka', 'Tandoori Chicken', 'Seekh Kebab'],
        originalPrice: 850,
        discountedPrice: 699
    },
    { 
        id: 3, 
        title: "Curry & Bread Combo", 
        description: "Your favorite curry paired with our freshly baked naan.", 
        imageUrl: 'https://i.ibb.co/HLC8nVwR/Gemini-Generated-Image-92vw8z92vw8z92vw.png',
        items: ['Butter Chicken', 'Garlic Naan (x2)'],
        originalPrice: 480,
        discountedPrice: 399
    },
];

export const MENU_ITEMS: MenuItem[] = [
    {
        id: 1,
        category: 'Starters',
        subCategory: 'Tandoori',
        name: 'Masala Papad',
        price: 80,
        description: 'Crispy papad topped with a spicy and tangy mixture of onions, tomatoes, and spices.',
        imageUrl: 'https://i.ibb.co/NBCJXxB/Gemini-Generated-Image-jqpcn8jqpcn8jqpc.png',
        dietary: Dietary.Veg,
        spiceLevel: 1,
        rating: 4.2,
        offerFlag: 'Bestseller'
    },
    {
        id: 2,
        category: 'Starters',
        subCategory: 'Tandoori',
        name: 'Paneer Tikka',
        price: 250,
        description: 'Cubes of paneer marinated in spices and grilled in a tandoor.',
        imageUrl: 'https://i.ibb.co/BV9MrfNf/Gemini-Generated-Image-2omf4t2omf4t2omf.png',
        dietary: Dietary.Veg,
        spiceLevel: 2,
        rating: 4.8,
        offerFlag: "Chef's Pick"
    },
    {
        id: 3,
        category: 'Starters',
        subCategory: 'Soups',
        name: 'Tomato Soup',
        price: 150,
        description: 'A creamy and tangy soup made from fresh, ripe tomatoes and aromatic herbs.',
        imageUrl: 'https://i.ibb.co/QjrYYQng/Gemini-Generated-Image-3ch1z63ch1z63ch1.png',
        dietary: Dietary.Veg,
        spiceLevel: 0,
        rating: 4.5,
    },
    {
        id: 4,
        category: 'Main Course',
        subCategory: 'Curries',
        name: 'Dal Makhani',
        price: 280,
        description: 'A classic North Indian dish made with black lentils, red kidney beans, butter, and cream.',
        imageUrl: 'https://i.ibb.co/4wnYk4pq/Gemini-Generated-Image-innu54innu54innu.png',
        dietary: Dietary.Veg,
        spiceLevel: 1,
        rating: 4.9,
        offerFlag: 'Bestseller'
    },
    {
        id: 5,
        category: 'Main Course',
        subCategory: 'Curries',
        name: 'Butter Chicken',
        price: 380,
        description: 'Grilled chicken cooked in a smooth, buttery, and creamy tomato-based gravy.',
        imageUrl: 'https://i.ibb.co/PsqQqXwc/Gemini-Generated-Image-t6row5t6row5t6ro.png',
        dietary: Dietary.NonVeg,
        spiceLevel: 1,
        rating: 4.9,
        offerFlag: "Chef's Pick"
    },
    {
        id: 6,
        category: 'Main Course',
        subCategory: 'Biryani',
        name: 'Chicken Biryani',
        price: 350,
        description: 'Aromatic basmati rice cooked with succulent chicken and a blend of exotic spices.',
        imageUrl: 'https://i.ibb.co/pBTTGmfG/Gemini-Generated-Image-ekvomdekvomdekvo.png',
        dietary: Dietary.NonVeg,
        spiceLevel: 2,
        rating: 4.8,
    },
    {
        id: 7,
        category: 'Main Course',
        subCategory: 'Chinese',
        name: 'Hakka Noodles',
        price: 220,
        description: 'Stir-fried noodles with a mix of fresh vegetables in a savory soy-based sauce.',
        imageUrl: 'https://i.ibb.co/3yvqPRHM/Gemini-Generated-Image-a38i8ia38i8ia38i.png',
        dietary: Dietary.Veg,
        spiceLevel: 1,
        rating: 4.4,
    },
    {
        id: 8,
        category: 'Main Course',
        subCategory: 'Breads',
        name: 'Garlic Naan',
        price: 100,
        description: 'Soft, fluffy Indian bread topped with fresh garlic and butter, baked in a tandoor.',
        imageUrl: 'https://i.ibb.co/2xVb1Mf/Gemini-Generated-Image-1c6wos1c6wos1c6w.png',
        dietary: Dietary.Veg,
        spiceLevel: 0,
        rating: 4.7,
    },
    {
        id: 9,
        category: 'Desserts',
        subCategory: 'Traditional',
        name: 'Gulab Jamun',
        price: 120,
        description: 'Soft, melt-in-your-mouth milk-solid-based sweets soaked in a fragrant sugar syrup.',
        imageUrl: 'https://i.ibb.co/MWV9fh1/Gemini-Generated-Image-ya2cv1ya2cv1ya2c.png',
        dietary: Dietary.Veg,
        spiceLevel: 0,
        rating: 4.9,
        offerFlag: 'Bestseller'
    },
    {
        id: 10,
        category: 'Desserts',
        subCategory: 'Cakes',
        name: 'Chocolate Lava Cake',
        price: 180,
        description: 'A decadent chocolate cake with a gooey, molten chocolate center.',
        imageUrl: 'https://i.ibb.co/tT4NdstR/Gemini-Generated-Image-hs0vfrhs0vfrhs0v.png',
        dietary: Dietary.Veg,
        spiceLevel: 0,
        rating: 4.8,
        offerFlag: 'New'
    },
    {
        id: 11,
        category: 'Drinks',
        subCategory: 'Hot',
        name: 'Masala Chai',
        price: 60,
        description: 'A classic Indian spiced tea that is aromatic and flavorful.',
        imageUrl: 'https://i.ibb.co/273qRyJT/Gemini-Generated-Image-7x6k377x6k377x6k.png',
        dietary: Dietary.Veg,
        spiceLevel: 0,
        rating: 4.7,
    },
    {
        id: 12,
        category: 'Drinks',
        subCategory: 'Cold',
        name: 'Mango Lassi',
        price: 140,
        description: 'A refreshing yogurt-based drink blended with sweet mango pulp.',
        imageUrl: 'https://i.ibb.co/s91q1S33/Gemini-Generated-Image-hark79hark79hark.png',
        dietary: Dietary.Veg,
        spiceLevel: 0,
        rating: 4.9,
        offerFlag: 'Special'
    },
    {
        id: 13,
        category: 'Main Course',
        subCategory: 'Biryani',
        name: 'Chicken Mandi',
        price: 380,
        description: 'A traditional Yemeni dish where tender chicken is slow-cooked with aromatic basmati rice and a unique blend of spices, smoked to perfection.',
        imageUrl: 'https://i.ibb.co/pB6xQ15w/Gemini-Generated-Image-9jv0aq9jv0aq9jv0.png',
        dietary: Dietary.NonVeg,
        spiceLevel: 1,
        rating: 4.8,
        offerFlag: 'New'
    },
    {
        id: 14,
        category: 'Main Course',
        subCategory: 'Biryani',
        name: 'Mutton Mandi',
        price: 450,
        description: 'Succulent mutton, slow-cooked until it falls off the bone, served over fragrant, spice-infused basmati rice with a smoky aroma.',
        imageUrl: 'https://i.ibb.co/yBnT3Cnp/Gemini-Generated-Image-11rv5i11rv5i11rv.png',
        dietary: Dietary.NonVeg,
        spiceLevel: 1,
        rating: 4.9,
        offerFlag: "Chef's Pick"
    },
    {
        id: 15,
        category: 'Main Course',
        subCategory: 'Biryani',
        name: 'Fish Mandi',
        price: 420,
        description: 'Delicate fillets of fish, marinated and cooked with fragrant basmati rice in the traditional Mandi style, offering a unique coastal twist.',
        imageUrl: 'https://i.ibb.co/Tq2ZK5S7/Gemini-Generated-Image-w4pom6w4pom6w4po.png',
        dietary: Dietary.NonVeg,
        spiceLevel: 1,
        rating: 4.7,
    }
];